version: '3.7'

services:
  stock-market-visualizer:
    container_name: stock-market-visualizer
    build: .
    command: python stock_market_visualizer/app/main.py
    ports:
      - 8000:8000
    depends_on:
      - redis
      - api
    environment:
      - DEBUG=True
      - REDIS_DB=0
    volumes:
      - .:/app

  api:
    container_name: sme-api-smv
    image: repo.treescale.com/xelicon/stock-market-engine:v0.1.1
    command: uvicorn stock_market_engine.api.main:app --host 0.0.0.0 --port 8001 --lifespan=on --use-colors --log-level debug
    ports:
      - 8001:8001
    environment:
      - REDIS_DB=0
    depends_on:
      - redis
      
  redis:
    container_name: redis-smv
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379