---
version: '3.7'

services:
  stock-market-visualizer:
    container_name: stock-market-visualizer
    build: .
    command: python stock_market_visualizer/app/main.py
    ports:
      - 8000:8000
    depends_on:
      - api
      - redis
    environment:
      - DEBUG=True
      - MAX_TICKER_SYMBOL_LENGTH=10
      - REDIS_DB=0
      - PORT=8000
      - SSL_KEYFILE=/certs/0.0.0.0-key.pem
      - SSL_CERTFILE=/certs/0.0.0.0.pem
      - DEFAULT_ENGINE_CONFIG=default_configs/puru_arkk_hedge.json
      - DEFAULT_VIEW_CONFIG=default_configs/view_config.json
      - TITLE=Is Puru ARKK hedged?
    volumes:
      - .:/app
      - ~/docker/certs:/certs

  api:
    container_name: sme-api-smv
    # image: repo.treescale.com/xelicon/stock-market-engine:v0.7.0
    image: stock-market-engine:v0.8.0
    command: >
      uvicorn
        stock_market_engine.main:app
        --host 0.0.0.0
        --port 8001
        --lifespan=on
        --use-colors
        --log-level debug
    ports:
      - 8001:8001
    environment:
      - REDIS_DB=1
      - MAX_TICKER_SYMBOL_LENGTH=10
    depends_on:
      - redis

  redis:
    container_name: redis-smv
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
