---
version: '3.7'

services:
  stock-market-visualizer:
    container_name: stock-market-visualizer
    image: xelicon/stock-market-visualizer:0.0.5
    command: python stock_market_visualizer/app/main.py
    ports:
      - 80:80
    depends_on:
      - stock-market-engine
      - redis
    environment:
      - MAX_TICKER_SYMBOL_LENGTH=10
      - REDIS_DB=0
      - PORT=80
      - DEFAULT_ENGINE_CONFIG=default_configs/puru_arkk_hedge.json
      - DEFAULT_VIEW_CONFIG=default_configs/view_config.json
      - TITLE=Is Puru ARKK hedged?
      - GTAG=G-LX4TC8NFDL

  stock-market-engine:
    container_name: sme-api-smv
    image: xelicon/stock-market-engine:0.0.8
    # yamllint disable-line rule:line-length
    command: uvicorn stock_market_engine.main:app --host 0.0.0.0 --port 8001 --lifespan=on --log-level warning
    ports:
      - 8001:8001
    environment:
      - REDIS_DB=1
      - MAX_TICKER_SYMBOL_LENGTH=10
      - STOCK_UPDATER=proxy
      - STOCK_UPDATER_CONFIG="http://stock-info-api:8002/ohlc"
    depends_on:
      - stock-info-api
      - redis

  stock-info-api:
    container_name: stock-info-api-smv
    image: xelicon/stock-info-api:0.0.3
    # yamllint disable-line rule:line-length
    command: uvicorn stock_info_api.main:app --host 0.0.0.0 --port 8002 --lifespan=on --log-level warning
    ports:
      - 8002:8002
    environment:
      - REDIS_DB=2
    depends_on:
      - redis

  redis:
    container_name: redis-stock-market-visualizer
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
