---
version: '3.7'

services:
  stock-market-visualizer:
    container_name: stock-market-visualizer
    build: .
    command: python stock_market_visualizer/app/main.py
    ports:
      - 8000:8000
    depends_on:
      - stock-market-engine
      - redis
    environment:
      - DEBUG=True
      - MAX_TICKER_SYMBOL_LENGTH=10
      - REDIS_DB=0
      - PORT=8000
      - SSL_KEYFILE=/certs/0.0.0.0-key.pem
      - SSL_CERTFILE=/certs/0.0.0.0.pem
      - DEFAULT_ENGINE_CONFIG=default_configs/puru_arkk_hedge.json
      - DEFAULT_VIEW_CONFIG=default_configs/view_config.json
      - TITLE=Is Puru ARKK hedged?
      - GTAG=G-FLX5TCEPQS
    volumes:
      - .:/app
      - ~/docker/certs:/certs

  stock-market-engine:
    container_name: sme-api-smv
    image: xelicon/stock-market-engine:latest-dev
    command: >
      uvicorn
        stock_market_engine.main:app
        --host 0.0.0.0
        --port 8001
        --lifespan=on
        --use-colors
        --log-level debug
    ports:
      - 8001:8001
    environment:
      - REDIS_DB=1
      - MAX_TICKER_SYMBOL_LENGTH=10
      - STOCK_UPDATER=proxy
      - STOCK_UPDATER_CONFIG="http://stock-info-api-smv:8002/ohlc"
    depends_on:
      - stock-info-api
      - redis

  stock-info-api:
    container_name: stock-info-api-smv
    image: xelicon/stock-info-api:0.0.3
    command: >
      uvicorn
        stock_info_api.main:app
        --host 0.0.0.0
        --port 8002
        --lifespan=on
        --use-colors
        --log-level debug
        --reload
    ports:
      - 8002:8002
    environment:
      - REDIS_DB=2
    depends_on:
      - redis

  redis:
    container_name: redis-stock-market-visualizer
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
