[build-system]
requires = ["setuptools>=58.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
experimental-string-processing = true
extend-exclude = '(\.env)|(\.egg-info)'